from pydantic import BaseModel, ConfigDict, Field


class SQLGeneration(BaseModel):
    """
    Contract for SQL generated by the LLM.
    """

    model_config = ConfigDict(extra="forbid")

    sql: str = Field(
        min_length=1,
        max_length=20_000,
        description="A single PostgreSQL SELECT statement.",
    )