import re
from langchain_core.messages import HumanMessage, SystemMessage

from app.llm.ollama import get_llm
from app.llm.prompts import SQL_SYSTEM_PROMPT, SQL_USER_PROMPT


def clean_sql_output(raw_sql: str) -> str:
    cleaned = raw_sql.strip()
    # Remove markdown code fences if generated by the LLM
    cleaned = re.sub(r"^```(?:sql)?\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    return cleaned.strip()


async def generate_sql(
    user_query: str,
    schema: str,
) -> str:
    llm = get_llm()

    messages = [
        SystemMessage(
            content=SQL_SYSTEM_PROMPT.format(
                schema=schema,
            )
        ),
        HumanMessage(
            content=SQL_USER_PROMPT.format(
                user_query=user_query,
            )
        ),
    ]

    response = await llm.ainvoke(messages)

    content = response.content

    if not isinstance(content, str):
        raise TypeError(
            "Expected LLM response content to be a string."
        )

    return clean_sql_output(content)